#!/bin/env sh

# A method to echo and run some command line
echo_and_run() { echo "$@" ; "$@" ; }

# Below the script

if (($EUID == 0)); then

    echo_and_run sudo systemctl enable rfkill-block@bluetooth.service

    exit

else 
    if (($EUID != 0)); then
        sudo $0 $@
    fi

    exit
fi
        

