#!/usr/bin/perl -w


#### Usage:
##       ./normUTF8 [filename with wrong encoding]
## so to use in all files of the current directory:
##       find . -type f -exec ~/normUTF8 {} \;
################################################################################
 

use strict;
use warnings;
use bytes;
use Encode;              #pgk: perl-encode-detect (AUR)
require Encode::Detect; 

my $fname = $ARGV[0];

if(not defined $fname){
    die "Filename needed as argument.\n";
}

sub normalize_to_utf8{
	return decode("Detect", shift);
}

my $fname_utf8 = normalize_to_utf8($fname);

if($fname ne $fname_utf8){
    system("mv", $fname, $fname_utf8);
}
             
